---
title: lichin-lin,front-end
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:categories/:year/:month/:day/:title"
exclude:
- ".rvmrc"
- ".rbenv-version"
- README.md
- Rakefile
- changelog.md
highlighter: rouge
tagline: Site Tagline
author:
  name: lichin-lin
  email: vic20087cjimlin@gmail.com
  github: lichin-lin
production_url: http://lichin-lin.github.io
url: https://lichin.me
enforce_ssl: lichin.me
future: true
paginate: 5
paginate_path: page:num
gems:
- jekyll-paginate
JB:
  version: 0.3.0
  THEME: twitter
  BASE_PATH: false
  ASSET_PATH: false
  archive_path: "/archive.html"
  categories_path: "/categories.html"
  tags_path: "/tags.html"
  atom_path: "/atom.xml"
  rss_path: "/rss.xml"
  comments:
    provider: disqus
    disqus:
      short_name: jekyllbootstrap
    livefyre:
      site_id: 123
    intensedebate:
      account: 123abc
    facebook:
      appid: 123
      num_posts: 5
      width: 580
      colorscheme: light
    duoshuo:
      short_name: jekyllbootstrap
  analytics:
    provider: google
    gauges:
      site_id: SITE ID
    google:
      tracking_id: UA-123-12
    getclicky:
      site_id: 
    mixpanel:
      token: _MIXPANEL_TOKEN_
    piwik:
      baseURL: myserver.tld/piwik
      idsite: '1'
  sharing:
    provider: false
